version: '3.8'

services:
  frontend:
    build: ./frontend
    restart: always
    ports:
      - '3000:3000'
    networks:
      - my-network
    volumes:
      - /app/node_modules
      - ./frontend:/app
  api:
    build: ./api
    restart: always
    ports:
      - '5555:5000'
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - my-network
    volumes:
      - /app/node_modules
      - ./api:/app
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - my-network
  adminer:
    image: adminer
    restart: always
    ports:
      - '8888:8080'
    networks:
      - my-network
volumes:
  mysql_data:
networks:
  my-network:
    driver: bridge

